### ISSUE TITLE
Setup Github Action to Automate Deployment

### ISSUE THREAD

**Issue by jimjeffers** [levisimons/eDNAExplorer#6]
This is a placeholder for a high priority issue. I'm going to research some tools to handle automated deployments of this project to our Jetstream instance via GitHub actions. @levisimons you may have to transfer ownership of this repo to my org as I have a paid account that already has credits for actions. This will be a significant change in the way you deploy and work on this scripts. We will begin pushing code to this repository and GitHub will automatically update the server whenever the main branch is updated.

**Comment by jimjeffers** [comment]
### 1. Recommended Tool

rsync over SSH

### 2. Sample GitHub Action

Here's a .github/workflows/deploy.yml file example using rsync:

```yaml
name: Deploy to Production Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Deploy to Production
      run: |
        rsync -r --delete-after --quiet ${{ github.workspace }}/ username@your-server:/path/to/deploy/
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
```

### 3. GitHub Secrets

DEPLOY_KEY: This will hold the private SSH key that has access to the remote server.

**Steps to Add Secrets:**

1. Go to this GitHub repository.
2. Navigate to Settings -> Secrets.
3. Add the secret named DEPLOY_KEY with the SSH private key content.

**Additional Secure Setup:**

On the server, you may want to create a specific user with restricted permissions, which can only access the deployment directory.

Convert the private key to a GitHub-recognized format by running ssh-keygen -p -m PEM -f ~/.ssh/your_key locally.
With this setup, each time you push to the main branch, the GitHub Action will automatically sync our repo with our Ubuntu machine.
